spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:adm_videos_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-inicialization: true
  h2:
    console:
      enabled: true
      path: /h2