version: '3.8'

services:
  mysql:
    container_name: admin_videos_mysql
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
      - MYSQL_USER=usr_videos
      - MYSQL_PASSWORD=123456
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - adm_videos_network

  phpmyadmin:
    container_name: admin_videos_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    networks:
      - adm_videos_network


networks:
  adm_videos_network:
    driver: bridge